image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - build
  - test
  - archive_artifacts
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy_artifactory:
  stage: archive_artifacts
  script:
    - mvn $MAVEN_CLI_OPTS deploy

deploy_prod:
  stage: deploy
  script:
    - mvn $MAVEN_CLI_OPTS clean install -PautoInstallBundle
    - mvn $MAVEN_CLI_OPTS clean install -PautoInstallPackage
  environment:
    name: production
    url: http://kkauthor.yebbare.com:4502/
  when: manual
  only:
    - master